### ISSUE TITLE
Adding setters does not actual add 'setters'

### ISSUE THREAD

**Issue by chrisknoll** [fillumina/netbeans-builder-module#1]
This is describe in the document, so not a bug per-se, but if you are going to add setters, shouldn't they be 'setXXX()'?

**Comment by fillumina** [comment]
Please check the article about fluent interface on wikipedia:
https://en.wikipedia.org/wiki/Fluent_interface#Java
sometimes the setXXX, getXXX convention is just inconvenient and doesn't add to the readability of the code. Of course this isn't general it's only that there are already very good setters/getters generators around and I needed a _fluent_ setters generator...

**Comment by chrisknoll** [comment]
Ok, Fair enough. thank you.

**Comment by fillumina** [comment]
I'm sorry for the (extreme) delay, google just buried this email under a
pile of garbage...
Then, this plugin it's all about fluent interfaces, there is already a
netbeans one to create standard setters and getters.
With fluent interfaces you tend to use the name of the property without
'set'.
Please refer to wikipedia:
https://en.wikipedia.org/wiki/Fluent_interface#Java

regards,
Francesco
