### ISSUE TITLE
Not working with JDK 14 on NetBeans 11.3 or 12.

### ISSUE THREAD

**Issue by Yaytay** [fillumina/netbeans-builder-module#2]
Hi,
I love this plugin and have been continuing to use it despite it only claiming to support Netbeans 8, but now it seems it's come to the end of the line and it doesn't work in Netbeans 12 beta 4 with JDK 14.
Are you still supporting it?
Thanks.

**Comment by fillumina** [comment]
Thanks for letting me know. I use this plugin myself but my current configuration is NB 11.3 with JDK 11 at the moment. I will test your configuration as soon as possible. I definitely intend to support the plugin for the future.
Thanks for your interest.
Francesco

**Comment by fillumina** [comment]
I have just tested the plugin with nb 12 openjdk 14.0.1 on ubuntu 20.04 and it works fine.
